version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_caja_cs
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: CajaCS
      MYSQL_USER: cajacs_user
      MYSQL_PASSWORD: cajacs_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
